sudo: required
services:
  - docker

before_install:
  - docker build -t jenybo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jenybo/react-test npm test

after_success:
  - docker build -t jenybo/multi-client ./client
  - docker build -t jenybo/multi-nginx ./nginx
  - docker build -t jenybo/multi-server ./server
  - docker build -t jenybo/multi-worker ./worker